//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Jobs.JYHWSDL
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.hhsd.com/xml/ckOrder",
        ConfigurationName = "StockOutOrderPort")]
    public interface StockOutOrderPort
    {

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<CKOrderResponse1> CKOrderAsync(CKOrderRequest1 request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hhsd.com/xml/ckOrder")]
    public partial class CKOrderRequest
    {

        private long headIdField;

        private string documentTypeField;

        private string documentNumberField;

        private string managerIdField;

        private string ouCodeField;

        private string organizationCodeField;

        private string itemIdField;

        private string businessTypeField;

        private System.DateTime exitEntryDateField;

        private System.DateTime creationDateField;

        private string departmentIdField;

        private RequestCKRow[] requestCKRowsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public long headId
        {
            get { return this.headIdField; }
            set { this.headIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string documentType
        {
            get { return this.documentTypeField; }
            set { this.documentTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string documentNumber
        {
            get { return this.documentNumberField; }
            set { this.documentNumberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string managerId
        {
            get { return this.managerIdField; }
            set { this.managerIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string ouCode
        {
            get { return this.ouCodeField; }
            set { this.ouCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string organizationCode
        {
            get { return this.organizationCodeField; }
            set { this.organizationCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string itemId
        {
            get { return this.itemIdField; }
            set { this.itemIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string businessType
        {
            get { return this.businessTypeField; }
            set { this.businessTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public System.DateTime exitEntryDate
        {
            get { return this.exitEntryDateField; }
            set { this.exitEntryDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public System.DateTime creationDate
        {
            get { return this.creationDateField; }
            set { this.creationDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string departmentId
        {
            get { return this.departmentIdField; }
            set { this.departmentIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("requestCKRows", IsNullable = true, Order = 11)]
        public RequestCKRow[] requestCKRows
        {
            get { return this.requestCKRowsField; }
            set { this.requestCKRowsField = value; }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.hhsd.com/xml/ckOrder")]
    public partial class RequestCKRow
    {

        private long lineIdField;

        private long headIdField;

        private int lineNumberField;

        private long sourceLineIdField;

        private string materialIdField;

        private double processingQuantityField;

        private string taskIdField;

        private string expenditureTypeField;

        private string inventoryCodeField;

        private string possessorIdField;

        private string remarkField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public long lineId
        {
            get { return this.lineIdField; }
            set { this.lineIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public long headId
        {
            get { return this.headIdField; }
            set { this.headIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public int lineNumber
        {
            get { return this.lineNumberField; }
            set { this.lineNumberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public long sourceLineId
        {
            get { return this.sourceLineIdField; }
            set { this.sourceLineIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string materialId
        {
            get { return this.materialIdField; }
            set { this.materialIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public double processingQuantity
        {
            get { return this.processingQuantityField; }
            set { this.processingQuantityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string taskId
        {
            get { return this.taskIdField; }
            set { this.taskIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string expenditureType
        {
            get { return this.expenditureTypeField; }
            set { this.expenditureTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string inventoryCode
        {
            get { return this.inventoryCodeField; }
            set { this.inventoryCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string possessorId
        {
            get { return this.possessorIdField; }
            set { this.possessorIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 10)]
        public string remark
        {
            get { return this.remarkField; }
            set { this.remarkField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hhsd.com/xml/ckOrder")]
    public partial class CKOrderResponse
    {

        private string codeField;

        private string dataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string code
        {
            get { return this.codeField; }
            set { this.codeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string data
        {
            get { return this.dataField; }
            set { this.dataField = value; }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class CKOrderRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hhsd.com/xml/ckOrder", Order = 0)]
        public CKOrderRequest CKOrderRequest;

        public CKOrderRequest1()
        {
        }

        public CKOrderRequest1(CKOrderRequest CKOrderRequest)
        {
            this.CKOrderRequest = CKOrderRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class CKOrderResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hhsd.com/xml/ckOrder", Order = 0)]
        public CKOrderResponse CKOrderResponse;

        public CKOrderResponse1()
        {
        }

        public CKOrderResponse1(CKOrderResponse CKOrderResponse)
        {
            this.CKOrderResponse = CKOrderResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface StockOutOrderPortChannel : StockOutOrderPort, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class StockOutOrderPortClient : System.ServiceModel.ClientBase<StockOutOrderPort>, StockOutOrderPort
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint,
            System.ServiceModel.Description.ClientCredentials clientCredentials);

        public StockOutOrderPortClient() :
            base(StockOutOrderPortClient.GetDefaultBinding(), StockOutOrderPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.StockOutOrderPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public StockOutOrderPortClient(EndpointConfiguration endpointConfiguration) :
            base(StockOutOrderPortClient.GetBindingForEndpoint(endpointConfiguration),
                StockOutOrderPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public StockOutOrderPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
            base(StockOutOrderPortClient.GetBindingForEndpoint(endpointConfiguration),
                new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public StockOutOrderPortClient(EndpointConfiguration endpointConfiguration,
            System.ServiceModel.EndpointAddress remoteAddress) :
            base(StockOutOrderPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public StockOutOrderPortClient(System.ServiceModel.Channels.Binding binding,
            System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CKOrderResponse1> StockOutOrderPort.CKOrderAsync(CKOrderRequest1 request)
        {
            return base.Channel.CKOrderAsync(request);
        }

        public System.Threading.Tasks.Task<CKOrderResponse1> CKOrderAsync(CKOrderRequest CKOrderRequest)
        {
            CKOrderRequest1 inValue = new CKOrderRequest1();
            inValue.CKOrderRequest = CKOrderRequest;
            return ((StockOutOrderPort) (this)).CKOrderAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(
                ((System.ServiceModel.ICommunicationObject) (this)).BeginOpen(null, null),
                new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject) (this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(
                ((System.ServiceModel.ICommunicationObject) (this)).BeginClose(null, null),
                new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject) (this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(
            EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.StockOutOrderPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.",
                endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(
            EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.StockOutOrderPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.14.204:19240/ws/stockout-order");
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.",
                endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return StockOutOrderPortClient.GetBindingForEndpoint(EndpointConfiguration.StockOutOrderPortSoap11);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return StockOutOrderPortClient.GetEndpointAddress(EndpointConfiguration.StockOutOrderPortSoap11);
        }

        public enum EndpointConfiguration
        {

            StockOutOrderPortSoap11,
        }
    }
}