//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Jobs.JYHWSDL
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.hhsd.com/xml/rtOrder",
        ConfigurationName = "InboundReturnsPort")]
    public interface InboundReturnsPort
    {

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<RTOrderResponse1> RTOrderAsync(RTOrderRequest1 request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hhsd.com/xml/rtOrder")]
    public partial class RTOrderRequest
    {

        private long headIdField;

        private string documentTypeField;

        private string documentNumberField;

        private string managerIdField;

        private string ouCodeField;

        private string organizationCodeField;

        private string vendorIdField;

        private string vendorSiteIdField;

        private string currencyField;

        private string businessTypeField;

        private double totalAmountField;

        private System.DateTime exitEntryDateField;

        private System.DateTime creationDateField;

        private string remarkField;

        private RequestRTRow[] requestRTRowsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public long headId
        {
            get { return this.headIdField; }
            set { this.headIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string documentType
        {
            get { return this.documentTypeField; }
            set { this.documentTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string documentNumber
        {
            get { return this.documentNumberField; }
            set { this.documentNumberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string managerId
        {
            get { return this.managerIdField; }
            set { this.managerIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string ouCode
        {
            get { return this.ouCodeField; }
            set { this.ouCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string organizationCode
        {
            get { return this.organizationCodeField; }
            set { this.organizationCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string vendorId
        {
            get { return this.vendorIdField; }
            set { this.vendorIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string vendorSiteId
        {
            get { return this.vendorSiteIdField; }
            set { this.vendorSiteIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string currency
        {
            get { return this.currencyField; }
            set { this.currencyField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string businessType
        {
            get { return this.businessTypeField; }
            set { this.businessTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public double totalAmount
        {
            get { return this.totalAmountField; }
            set { this.totalAmountField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public System.DateTime exitEntryDate
        {
            get { return this.exitEntryDateField; }
            set { this.exitEntryDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public System.DateTime creationDate
        {
            get { return this.creationDateField; }
            set { this.creationDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 13)]
        public string remark
        {
            get { return this.remarkField; }
            set { this.remarkField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("requestRTRows", Order = 14)]
        public RequestRTRow[] requestRTRows
        {
            get { return this.requestRTRowsField; }
            set { this.requestRTRowsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.hhsd.com/xml/rtOrder")]
    public partial class RequestRTRow
    {

        private long lineIdField;

        private long headIdField;

        private int lineNumberField;

        private long sourceLineIdField;

        private string materialIdField;

        private double processingQuantityField;

        private string currencyField;

        private double priceField;

        private double amountField;

        private string itemIdField;

        private string taskIdField;

        private string expenditureTypeField;

        private string inventoryCodeField;

        private string remarkField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public long lineId
        {
            get { return this.lineIdField; }
            set { this.lineIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public long headId
        {
            get { return this.headIdField; }
            set { this.headIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public int lineNumber
        {
            get { return this.lineNumberField; }
            set { this.lineNumberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public long sourceLineId
        {
            get { return this.sourceLineIdField; }
            set { this.sourceLineIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string materialId
        {
            get { return this.materialIdField; }
            set { this.materialIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public double processingQuantity
        {
            get { return this.processingQuantityField; }
            set { this.processingQuantityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string currency
        {
            get { return this.currencyField; }
            set { this.currencyField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public double price
        {
            get { return this.priceField; }
            set { this.priceField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public double amount
        {
            get { return this.amountField; }
            set { this.amountField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string itemId
        {
            get { return this.itemIdField; }
            set { this.itemIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string taskId
        {
            get { return this.taskIdField; }
            set { this.taskIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string expenditureType
        {
            get { return this.expenditureTypeField; }
            set { this.expenditureTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string inventoryCode
        {
            get { return this.inventoryCodeField; }
            set { this.inventoryCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 13)]
        public string remark
        {
            get { return this.remarkField; }
            set { this.remarkField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hhsd.com/xml/rtOrder")]
    public partial class RTOrderResponse
    {

        private string codeField;

        private string dataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string code
        {
            get { return this.codeField; }
            set { this.codeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string data
        {
            get { return this.dataField; }
            set { this.dataField = value; }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RTOrderRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hhsd.com/xml/rtOrder", Order = 0)]
        public RTOrderRequest RTOrderRequest;

        public RTOrderRequest1()
        {
        }

        public RTOrderRequest1(RTOrderRequest RTOrderRequest)
        {
            this.RTOrderRequest = RTOrderRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RTOrderResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hhsd.com/xml/rtOrder", Order = 0)]
        public RTOrderResponse RTOrderResponse;

        public RTOrderResponse1()
        {
        }

        public RTOrderResponse1(RTOrderResponse RTOrderResponse)
        {
            this.RTOrderResponse = RTOrderResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface InboundReturnsPortChannel : InboundReturnsPort, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class InboundReturnsPortClient : System.ServiceModel.ClientBase<InboundReturnsPort>,
        InboundReturnsPort
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint,
            System.ServiceModel.Description.ClientCredentials clientCredentials);

        public InboundReturnsPortClient() :
            base(InboundReturnsPortClient.GetDefaultBinding(), InboundReturnsPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.InboundReturnsPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public InboundReturnsPortClient(EndpointConfiguration endpointConfiguration) :
            base(InboundReturnsPortClient.GetBindingForEndpoint(endpointConfiguration),
                InboundReturnsPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public InboundReturnsPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
            base(InboundReturnsPortClient.GetBindingForEndpoint(endpointConfiguration),
                new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public InboundReturnsPortClient(EndpointConfiguration endpointConfiguration,
            System.ServiceModel.EndpointAddress remoteAddress) :
            base(InboundReturnsPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public InboundReturnsPortClient(System.ServiceModel.Channels.Binding binding,
            System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RTOrderResponse1> InboundReturnsPort.RTOrderAsync(RTOrderRequest1 request)
        {
            return base.Channel.RTOrderAsync(request);
        }

        public System.Threading.Tasks.Task<RTOrderResponse1> RTOrderAsync(RTOrderRequest RTOrderRequest)
        {
            RTOrderRequest1 inValue = new RTOrderRequest1();
            inValue.RTOrderRequest = RTOrderRequest;
            return ((InboundReturnsPort) (this)).RTOrderAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(
                ((System.ServiceModel.ICommunicationObject) (this)).BeginOpen(null, null),
                new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject) (this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(
                ((System.ServiceModel.ICommunicationObject) (this)).BeginClose(null, null),
                new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject) (this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(
            EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.InboundReturnsPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.",
                endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(
            EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.InboundReturnsPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.14.205:19240/ws/inbound-returns");
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.",
                endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InboundReturnsPortClient.GetBindingForEndpoint(EndpointConfiguration.InboundReturnsPortSoap11);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InboundReturnsPortClient.GetEndpointAddress(EndpointConfiguration.InboundReturnsPortSoap11);
        }

        public enum EndpointConfiguration
        {

            InboundReturnsPortSoap11,
        }
    }

}
