//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web.Jobs.JYHWSDL
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.hhsd.com/xml/tkOrder",
        ConfigurationName = "WithdrawalPort")]
    public interface WithdrawalPort
    {

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TKOrderResponse1> TKOrderAsync(TKOrderRequest1 request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hhsd.com/xml/tkOrder")]
    public partial class TKOrderRequest
    {

        private long headIdField;

        private string documentTypeField;

        private string documentNumberField;

        private string managerIdField;

        private string ouCodeField;

        private string organizationCodeField;

        private string itemIdField;

        private string businessTypeField;

        private System.DateTime exitEntryDateField;

        private System.DateTime creationDateField;

        private string departmentIdField;

        private RequestTKRow[] requestTKRowsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public long headId
        {
            get { return this.headIdField; }
            set { this.headIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string documentType
        {
            get { return this.documentTypeField; }
            set { this.documentTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string documentNumber
        {
            get { return this.documentNumberField; }
            set { this.documentNumberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string managerId
        {
            get { return this.managerIdField; }
            set { this.managerIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string ouCode
        {
            get { return this.ouCodeField; }
            set { this.ouCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string organizationCode
        {
            get { return this.organizationCodeField; }
            set { this.organizationCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string itemId
        {
            get { return this.itemIdField; }
            set { this.itemIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string businessType
        {
            get { return this.businessTypeField; }
            set { this.businessTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public System.DateTime exitEntryDate
        {
            get { return this.exitEntryDateField; }
            set { this.exitEntryDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public System.DateTime creationDate
        {
            get { return this.creationDateField; }
            set { this.creationDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string departmentId
        {
            get { return this.departmentIdField; }
            set { this.departmentIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("requestTKRows", Order = 11)]
        public RequestTKRow[] requestTKRows
        {
            get { return this.requestTKRowsField; }
            set { this.requestTKRowsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.hhsd.com/xml/tkOrder")]
    public partial class RequestTKRow
    {

        private long lineIdField;

        private long headIdField;

        private int lineNumberField;

        private long sourceLineIdField;

        private string materialIdField;

        private double processingQuantityField;

        private string taskIdField;

        private string expenditureTypeField;

        private string inventoryCodeField;

        private string possessorIdField;

        private string remarkField;

        private string itemIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public long lineId
        {
            get { return this.lineIdField; }
            set { this.lineIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public long headId
        {
            get { return this.headIdField; }
            set { this.headIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public int lineNumber
        {
            get { return this.lineNumberField; }
            set { this.lineNumberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public long sourceLineId
        {
            get { return this.sourceLineIdField; }
            set { this.sourceLineIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string materialId
        {
            get { return this.materialIdField; }
            set { this.materialIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public double processingQuantity
        {
            get { return this.processingQuantityField; }
            set { this.processingQuantityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string taskId
        {
            get { return this.taskIdField; }
            set { this.taskIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string expenditureType
        {
            get { return this.expenditureTypeField; }
            set { this.expenditureTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string inventoryCode
        {
            get { return this.inventoryCodeField; }
            set { this.inventoryCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string possessorId
        {
            get { return this.possessorIdField; }
            set { this.possessorIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 10)]
        public string remark
        {
            get { return this.remarkField; }
            set { this.remarkField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string itemId
        {
            get { return this.itemIdField; }
            set { this.itemIdField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hhsd.com/xml/tkOrder")]
    public partial class TKOrderResponse
    {

        private string codeField;

        private string dataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string code
        {
            get { return this.codeField; }
            set { this.codeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string data
        {
            get { return this.dataField; }
            set { this.dataField = value; }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class TKOrderRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hhsd.com/xml/tkOrder", Order = 0)]
        public TKOrderRequest TKOrderRequest;

        public TKOrderRequest1()
        {
        }

        public TKOrderRequest1(TKOrderRequest TKOrderRequest)
        {
            this.TKOrderRequest = TKOrderRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class TKOrderResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hhsd.com/xml/tkOrder", Order = 0)]
        public TKOrderResponse TKOrderResponse;

        public TKOrderResponse1()
        {
        }

        public TKOrderResponse1(TKOrderResponse TKOrderResponse)
        {
            this.TKOrderResponse = TKOrderResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface WithdrawalPortChannel : WithdrawalPort, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class WithdrawalPortClient : System.ServiceModel.ClientBase<WithdrawalPort>, WithdrawalPort
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint,
            System.ServiceModel.Description.ClientCredentials clientCredentials);

        public WithdrawalPortClient() :
            base(WithdrawalPortClient.GetDefaultBinding(), WithdrawalPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WithdrawalPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WithdrawalPortClient(EndpointConfiguration endpointConfiguration) :
            base(WithdrawalPortClient.GetBindingForEndpoint(endpointConfiguration),
                WithdrawalPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WithdrawalPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
            base(WithdrawalPortClient.GetBindingForEndpoint(endpointConfiguration),
                new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WithdrawalPortClient(EndpointConfiguration endpointConfiguration,
            System.ServiceModel.EndpointAddress remoteAddress) :
            base(WithdrawalPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WithdrawalPortClient(System.ServiceModel.Channels.Binding binding,
            System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TKOrderResponse1> WithdrawalPort.TKOrderAsync(TKOrderRequest1 request)
        {
            return base.Channel.TKOrderAsync(request);
        }

        public System.Threading.Tasks.Task<TKOrderResponse1> TKOrderAsync(TKOrderRequest TKOrderRequest)
        {
            TKOrderRequest1 inValue = new TKOrderRequest1();
            inValue.TKOrderRequest = TKOrderRequest;
            return ((WithdrawalPort) (this)).TKOrderAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(
                ((System.ServiceModel.ICommunicationObject) (this)).BeginOpen(null, null),
                new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject) (this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(
                ((System.ServiceModel.ICommunicationObject) (this)).BeginClose(null, null),
                new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject) (this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(
            EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WithdrawalPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.",
                endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(
            EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WithdrawalPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://10.78.75.11:19240/ws/withdrawal");
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.",
                endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WithdrawalPortClient.GetBindingForEndpoint(EndpointConfiguration.WithdrawalPortSoap11);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WithdrawalPortClient.GetEndpointAddress(EndpointConfiguration.WithdrawalPortSoap11);
        }

        public enum EndpointConfiguration
        {

            WithdrawalPortSoap11,
        }
    }

}
